package migrator

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// GenerateMigration creates .up.sql and .down.sql files from diffs
func GenerateMigration(name string, models []*ModelSchema, dbSchemas map[string]*TableSchema, migrationsDir string) (string, string, error) {
	upSQL := strings.Builder{}
	downSQL := strings.Builder{}

	upSQL.WriteString("-- Auto-generated by gomigrate\n")
	upSQL.WriteString(fmt.Sprintf("-- Generated at: %s\n\n", time.Now().Format("2006-01-02 15:04:05")))
	downSQL.WriteString("-- Auto-generated by gomigrate\n")
	downSQL.WriteString(fmt.Sprintf("-- Generated at: %s\n\n", time.Now().Format("2006-01-02 15:04:05")))

	hasChanges := false

	for _, model := range models {
		dbSchema, exists := dbSchemas[model.TableName]

		if !exists || len(dbSchema.Columns) == 0 {
			up, down := generateCreateTable(model)
			upSQL.WriteString(up)
			downSQL.WriteString(down)
			hasChanges = true
			continue
		}

		diffs := Diff(model, dbSchema)
		if len(diffs) == 0 {
			continue
		}

		hasChanges = true
		up, down := generateAlterTable(diffs)
		upSQL.WriteString(up)
		downSQL.WriteString(down)
	}

	if !hasChanges {
		return "", "", nil
	}

	version := NextVersion(migrationsDir)
	upSQL.WriteString(fmt.Sprintf("\nSELECT '✅ %s_%s applied' AS status;\n", version, name))
	downSQL.WriteString(fmt.Sprintf("\nSELECT '✅ %s_%s rolled back' AS status;\n", version, name))

	upFile := filepath.Join(migrationsDir, fmt.Sprintf("%s_%s.up.sql", version, name))
	downFile := filepath.Join(migrationsDir, fmt.Sprintf("%s_%s.down.sql", version, name))

	if err := os.WriteFile(upFile, []byte(upSQL.String()), 0644); err != nil {
		return "", "", fmt.Errorf("writing up migration: %w", err)
	}
	if err := os.WriteFile(downFile, []byte(downSQL.String()), 0644); err != nil {
		return "", "", fmt.Errorf("writing down migration: %w", err)
	}

	return upFile, downFile, nil
}

// generateCreateTable generates CREATE TABLE SQL
func generateCreateTable(model *ModelSchema) (up, down string) {
	sb := strings.Builder{}
	sb.WriteString(fmt.Sprintf("-- Create table: %s\n", model.TableName))
	sb.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n", model.TableName))
	sb.WriteString("    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n")
	sb.WriteString("    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n")
	sb.WriteString("    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n")

	for i, field := range model.Fields {
		comma := ","
		if i == len(model.Fields)-1 {
			comma = ""
		}
		sb.WriteString(fmt.Sprintf("    %s\n", columnDefinition(field, comma)))
	}

	sb.WriteString(");\n\n")
	down = fmt.Sprintf("DROP TABLE IF EXISTS %s CASCADE;\n\n", model.TableName)
	return sb.String(), down
}

// generateAlterTable generates ALTER TABLE SQL for diffs
func generateAlterTable(diffs []ColumnDiff) (up, down string) {
	upSB := strings.Builder{}
	downSB := strings.Builder{}

	tableMap := map[string][]ColumnDiff{}
	for _, d := range diffs {
		tableMap[d.Table] = append(tableMap[d.Table], d)
	}

	tables := []string{}
	for t := range tableMap {
		tables = append(tables, t)
	}
	sort.Strings(tables)

	for _, table := range tables {
		upSB.WriteString(fmt.Sprintf("-- Alter table: %s\n", table))
		downSB.WriteString(fmt.Sprintf("-- Revert table: %s\n", table))

		for _, diff := range tableMap[table] {
			switch diff.ChangeType {
			case ChangeAdd:
				nullable := "NOT NULL"
				if diff.Nullable {
					nullable = ""
				}
				defaultVal := sqlDefault(diff.SQLType, diff.Nullable)
				checkConstraint := ""
				if len(diff.EnumValues) > 0 {
					checkConstraint = fmt.Sprintf("\n        CHECK (%s IN (%s))", diff.Column, quotedValues(diff.EnumValues))
					// First enum value becomes default
					defaultVal = fmt.Sprintf(" DEFAULT '%s'", diff.EnumValues[0])
				}
				upSB.WriteString(fmt.Sprintf(
					"ALTER TABLE %s ADD COLUMN IF NOT EXISTS %s %s %s%s%s;\n",
					diff.Table, diff.Column, diff.SQLType, nullable, defaultVal, checkConstraint,
				))
				downSB.WriteString(fmt.Sprintf(
					"ALTER TABLE %s DROP COLUMN IF EXISTS %s;\n",
					diff.Table, diff.Column,
				))

			case ChangeModify:
				upSB.WriteString(fmt.Sprintf(
					"ALTER TABLE %s ALTER COLUMN %s TYPE %s;\n",
					diff.Table, diff.Column, diff.NewType,
				))
				downSB.WriteString(fmt.Sprintf(
					"ALTER TABLE %s ALTER COLUMN %s TYPE %s;\n",
					diff.Table, diff.Column, diff.OldType,
				))
			}
		}
		upSB.WriteString("\n")
		downSB.WriteString("\n")
	}

	return upSB.String(), downSB.String()
}

// columnDefinition builds a full column definition string for CREATE TABLE
func columnDefinition(field StructField, comma string) string {
	nullable := "NOT NULL"
	if field.Nullable {
		nullable = ""
	}

	defaultVal := sqlDefault(field.SQLType, field.Nullable)
	checkConstraint := ""

	if len(field.EnumValues) > 0 {
		// First value is the default
		defaultVal = fmt.Sprintf(" DEFAULT '%s'", field.EnumValues[0])
		checkConstraint = fmt.Sprintf("\n        CHECK (%s IN (%s))", field.DBName, quotedValues(field.EnumValues))
	}

	return fmt.Sprintf("%s %s %s%s%s%s",
		field.DBName,
		field.SQLType,
		nullable,
		defaultVal,
		checkConstraint,
		comma,
	)
}

// quotedValues wraps enum values in single quotes for SQL
func quotedValues(values []string) string {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("'%s'", v)
	}
	return strings.Join(quoted, ", ")
}

// sqlDefault returns a sensible DEFAULT for a SQL type
func sqlDefault(sqlType string, nullable bool) string {
	if nullable {
		return ""
	}
	defaults := map[string]string{
		"TEXT":        " DEFAULT ''",
		"INTEGER":     " DEFAULT 0",
		"BIGINT":      " DEFAULT 0",
		"BOOLEAN":     " DEFAULT false",
		"FLOAT":       " DEFAULT 0",
		"TIMESTAMPTZ": "",
		"UUID":        "",
		"TEXT[]":      " DEFAULT '{}'",
	}
	if d, ok := defaults[sqlType]; ok {
		return d
	}
	return ""
}

// NextVersion calculates the next migration version number
func NextVersion(migrationsDir string) string {
	entries, err := os.ReadDir(migrationsDir)
	if err != nil {
		return "000001"
	}

	max := 0
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".up.sql") {
			var n int
			fmt.Sscanf(e.Name(), "%d", &n)
			if n > max {
				max = n
			}
		}
	}
	return fmt.Sprintf("%06d", max+1)
}
