package migrator

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// GenerateMigration creates .up.sql and .down.sql files from diffs
func GenerateMigration(name string, models []*ModelSchema, dbSchemas map[string]*TableSchema, migrationsDir string) (string, string, error) {
	upSQL := strings.Builder{}
	downSQL := strings.Builder{}

	upSQL.WriteString("-- Auto-generated by gomigrate\n")
	upSQL.WriteString(fmt.Sprintf("-- Generated at: %s\n\n", time.Now().Format("2006-01-02 15:04:05")))
	downSQL.WriteString("-- Auto-generated by gomigrate\n")
	downSQL.WriteString(fmt.Sprintf("-- Generated at: %s\n\n", time.Now().Format("2006-01-02 15:04:05")))

	hasChanges := false

	for _, model := range models {
		dbSchema, exists := dbSchemas[model.TableName]

		if !exists || len(dbSchema.Columns) == 0 {
			up, down := generateCreateTable(model)
			upSQL.WriteString(up)
			downSQL.WriteString(down)
			for _, idx := range collectIndexes(model) {
				upSQL.WriteString(generateCreateIndex(idx))
				downSQL.WriteString(generateDropIndex(idx))
			}
			hasChanges = true
			continue
		}

		diffs := Diff(model, dbSchema)
		idxDiffs := DiffIndexes(model, dbSchema)
		if len(diffs) == 0 && len(idxDiffs) == 0 {
			continue
		}
		hasChanges = true
		if len(diffs) > 0 {
			up, down := generateAlterTable(diffs)
			upSQL.WriteString(up)
			downSQL.WriteString(down)
		}
		for _, idx := range idxDiffs {
			upSQL.WriteString(generateCreateIndex(idx))
			downSQL.WriteString(generateDropIndex(idx))
		}
	}

	if !hasChanges {
		return "", "", nil
	}

	version := NextVersion(migrationsDir)
	upSQL.WriteString(fmt.Sprintf("\nSELECT '✅ %s_%s applied' AS status;\n", version, name))
	downSQL.WriteString(fmt.Sprintf("\nSELECT '✅ %s_%s rolled back' AS status;\n", version, name))

	upFile := filepath.Join(migrationsDir, fmt.Sprintf("%s_%s.up.sql", version, name))
	downFile := filepath.Join(migrationsDir, fmt.Sprintf("%s_%s.down.sql", version, name))

	if err := os.WriteFile(upFile, []byte(upSQL.String()), 0644); err != nil {
		return "", "", fmt.Errorf("writing up migration: %w", err)
	}
	if err := os.WriteFile(downFile, []byte(downSQL.String()), 0644); err != nil {
		return "", "", fmt.Errorf("writing down migration: %w", err)
	}

	return upFile, downFile, nil
}

// generateCreateTable generates CREATE TABLE SQL
func generateCreateTable(model *ModelSchema) (up, down string) {
	sb := strings.Builder{}
	sb.WriteString(fmt.Sprintf("-- Create table: %s\n", model.TableName))
	sb.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n", model.TableName))
	sb.WriteString("    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n")
	sb.WriteString("    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n")
	sb.WriteString("    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n")
	for i, field := range model.Fields {
		comma := ","
		if i == len(model.Fields)-1 {
			comma = ""
		}
		sb.WriteString(fmt.Sprintf("    %s\n", columnDefinition(field, comma)))
	}
	sb.WriteString(");\n\n")
	return sb.String(), fmt.Sprintf("DROP TABLE IF EXISTS %s CASCADE;\n\n", model.TableName)
}

// generateAlterTable generates ALTER TABLE SQL for column diffs
func generateAlterTable(diffs []ColumnDiff) (up, down string) {
	upSB := strings.Builder{}
	downSB := strings.Builder{}

	tableMap := map[string][]ColumnDiff{}
	for _, d := range diffs {
		tableMap[d.Table] = append(tableMap[d.Table], d)
	}
	tables := []string{}
	for t := range tableMap {
		tables = append(tables, t)
	}
	sort.Strings(tables)

	for _, table := range tables {
		upSB.WriteString(fmt.Sprintf("-- Alter table: %s\n", table))
		downSB.WriteString(fmt.Sprintf("-- Revert table: %s\n", table))

		for _, diff := range tableMap[table] {
			switch diff.ChangeType {
			case ChangeAdd:
				nullable := "NOT NULL"
				if diff.Nullable {
					nullable = ""
				}
				defaultVal := resolveDefault(diff.SQLType, diff.EnumValues, diff.Nullable)
				extras := buildExtras(diff.Column, diff.EnumValues, diff.References, diff.Unique)
				upSB.WriteString(fmt.Sprintf(
					"ALTER TABLE %s ADD COLUMN IF NOT EXISTS %s %s %s%s%s;\n",
					diff.Table, diff.Column, diff.SQLType, nullable, defaultVal, extras,
				))
				downSB.WriteString(fmt.Sprintf(
					"ALTER TABLE %s DROP COLUMN IF EXISTS %s;\n",
					diff.Table, diff.Column,
				))
			case ChangeModify:
				upSB.WriteString(fmt.Sprintf(
					"ALTER TABLE %s ALTER COLUMN %s TYPE %s;\n",
					diff.Table, diff.Column, diff.NewType,
				))
				downSB.WriteString(fmt.Sprintf(
					"ALTER TABLE %s ALTER COLUMN %s TYPE %s;\n",
					diff.Table, diff.Column, diff.OldType,
				))
			}
		}
		upSB.WriteString("\n")
		downSB.WriteString("\n")
	}
	return upSB.String(), downSB.String()
}

// columnDefinition builds a full column definition for CREATE TABLE
func columnDefinition(field StructField, comma string) string {
	nullable := "NOT NULL"
	if field.Nullable {
		nullable = ""
	}
	defaultVal := resolveDefault(field.SQLType, field.EnumValues, field.Nullable)
	extras := buildExtras(field.DBName, field.EnumValues, field.References, field.Unique)

	return fmt.Sprintf("%-30s %-15s %s%s%s%s",
		field.DBName, field.SQLType, nullable, defaultVal, extras, comma,
	)
}

// resolveDefault picks the right DEFAULT:
// - enum → first enum value
// - nullable → no default
// - otherwise → type default
func resolveDefault(sqlType string, enumValues []string, nullable bool) string {
	if len(enumValues) > 0 {
		return fmt.Sprintf(" DEFAULT '%s'", enumValues[0])
	}
	return sqlDefault(sqlType, nullable)
}

// buildExtras builds CHECK, REFERENCES, UNIQUE clauses
func buildExtras(colName string, enumValues []string, ref *FKRef, unique bool) string {
	sb := strings.Builder{}

	if len(enumValues) > 0 {
		sb.WriteString(fmt.Sprintf("\n        CHECK (%s IN (%s))", colName, quotedValues(enumValues)))
	}
	if ref != nil {
		onDelete := ref.OnDelete
		if onDelete == "" {
			onDelete = "RESTRICT"
		}
		sb.WriteString(fmt.Sprintf("\n        REFERENCES %s(%s) ON DELETE %s", ref.Table, ref.Column, onDelete))
	}
	if unique {
		sb.WriteString(" UNIQUE")
	}
	return sb.String()
}

// collectIndexes gathers all indexes needed for a model
func collectIndexes(model *ModelSchema) []IndexDef {
	indexes := []IndexDef{}
	for _, field := range model.Fields {
		if field.Index || field.References != nil {
			indexes = append(indexes, IndexDef{
				Table:   model.TableName,
				Columns: []string{field.DBName},
				Unique:  false,
				Name:    fmt.Sprintf("idx_%s_%s", model.TableName, field.DBName),
			})
		}
		if field.Unique {
			indexes = append(indexes, IndexDef{
				Table:   model.TableName,
				Columns: []string{field.DBName},
				Unique:  true,
				Name:    fmt.Sprintf("idx_%s_%s_unique", model.TableName, field.DBName),
			})
		}
	}
	return indexes
}

func generateCreateIndex(idx IndexDef) string {
	unique := ""
	if idx.Unique {
		unique = "UNIQUE "
	}
	return fmt.Sprintf("CREATE %sINDEX IF NOT EXISTS %s ON %s (%s);\n",
		unique, idx.Name, idx.Table, strings.Join(idx.Columns, ", "))
}

func generateDropIndex(idx IndexDef) string {
	return fmt.Sprintf("DROP INDEX IF EXISTS %s;\n", idx.Name)
}

func quotedValues(values []string) string {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("'%s'", v)
	}
	return strings.Join(quoted, ", ")
}

func sqlDefault(sqlType string, nullable bool) string {
	if nullable {
		return ""
	}
	defaults := map[string]string{
		"TEXT":        " DEFAULT ''",
		"INTEGER":     " DEFAULT 0",
		"BIGINT":      " DEFAULT 0",
		"BOOLEAN":     " DEFAULT false",
		"FLOAT":       " DEFAULT 0",
		"TIMESTAMPTZ": "",
		"UUID":        "",
		"TEXT[]":      " DEFAULT '{}'",
	}
	if d, ok := defaults[sqlType]; ok {
		return d
	}
	return ""
}

// NextVersion calculates the next migration version number
func NextVersion(migrationsDir string) string {
	entries, err := os.ReadDir(migrationsDir)
	if err != nil {
		return "000001"
	}
	max := 0
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".up.sql") {
			var n int
			fmt.Sscanf(e.Name(), "%d", &n)
			if n > max {
				max = n
			}
		}
	}
	return fmt.Sprintf("%06d", max+1)
}
